### PR TITLE
ns-don: disable sshd

### PR DESCRIPTION
**Pull request by gsanchietti**
Make sure OpenSSH doesn't try to start at boot

### CODE REVIEW

**Comment by gsanchietti** [comment]
Current patch doesn't work: the service is not disabled. 
Moving the command inside ns-don uci-default doesn't resolve the issue.

**Review by NethNick — COMMENTED** [review]
Want something earlier than level 99 ?

**Comment by gsanchietti** [comment]
> Want something earlier than level 99 ?

I do not think position is important: put it where it fit best.

> We could disable dropbear from running with:

We do not have to disable dropbear, but OpenSSH

**Comment by gsanchietti** [comment]
Replaced by #96

**Pull request closed without merging**
